---
# handlers file for manage_netplan
- name: "Generate netplan configuration"
  ansible.builtin.command: netplan generate
  changed_when: false
  become: true
  listen: "netplan-generate"

- name: "Apply netplan configuration"
  ansible.builtin.command: netplan apply
  listen: "netplan-apply"
  changed_when: false
  when: manage_netplan_apply
  become: true
